// ============================================================
// POST /api/elearning/session/generate
// ============================================================
// Generates a personalized e-learning session for a child.
// Auth: any authenticated user + child ownership check.
// Returns: session_id + full session plan.
// ============================================================

import { NextRequest, NextResponse } from 'next/server';
import { requireAuth, getServiceSupabase } from '@/lib/api-auth';
import { requireFeature } from '@/lib/features/require-feature';
import { buildELearningSession } from '@/lib/elearning/session-builder';
import crypto from 'crypto';

export const dynamic = 'force-dynamic';

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export async function POST(request: NextRequest) {
  const requestId = crypto.randomUUID();

  try {
    // ─── Auth ───
    const auth = await requireAuth();
    if (!auth.authorized) {
      return NextResponse.json({ error: auth.error }, { status: auth.email ? 403 : 401 });
    }

    // ─── Parse body ───
    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
    }

    const { child_id } = body as { child_id?: string };
    if (!child_id || !UUID_RE.test(child_id)) {
      return NextResponse.json({ error: 'Valid child_id (UUID) is required' }, { status: 400 });
    }

    const denied = await requireFeature('elearning_access', child_id);
    if (denied) return denied;

    console.log(JSON.stringify({ requestId, event: 'elearning_session_generate_start', childId: child_id }));

    const supabase = getServiceSupabase();

    // ─── Child ownership check ───
    const { data: child } = await supabase
      .from('children')
      .select('id, parent_email, parent_id')
      .eq('id', child_id)
      .single();

    if (!child) {
      return NextResponse.json({ error: 'Child not found' }, { status: 404 });
    }

    const isOwner =
      (child.parent_email && child.parent_email === auth.email) ||
      (child.parent_id && child.parent_id === auth.userId);

    if (!isOwner) {
      return NextResponse.json({ error: 'Not authorized for this child' }, { status: 403 });
    }

    // ─── Build session ───
    const sessionPlan = await buildELearningSession(child_id);

    // ─── Check if any content was generated by Gemini ───
    const intelligenceGenerated = Object.values(sessionPlan.content_sources).some(
      src => src === 'generated',
    );

    // ─── Persist to elearning_sessions ───
    const { data: session, error: insertErr } = await supabase
      .from('elearning_sessions' as any)
      .insert({
        child_id,
        session_plan: sessionPlan as any,
        content_ids_used: [] as any,
        intelligence_context: sessionPlan.intelligence_context as any,
        total_segments: sessionPlan.segments.length,
        intelligence_generated: intelligenceGenerated,
        estimated_minutes: sessionPlan.estimated_minutes,
      } as any)
      .select('id')
      .single();

    if (insertErr) {
      console.error(JSON.stringify({ requestId, event: 'elearning_session_insert_error', error: insertErr.message }));
      return NextResponse.json({ error: 'Failed to save session' }, { status: 500 });
    }

    console.log(JSON.stringify({
      requestId, event: 'elearning_session_generated',
      sessionId: (session as any)?.id, childId: child_id,
      sources: sessionPlan.content_sources,
      segments: sessionPlan.segments.length,
    }));

    return NextResponse.json({
      success: true,
      session_id: (session as any)?.id,
      session_plan: sessionPlan,
    }, { status: 201 });

  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.error(JSON.stringify({ requestId, event: 'elearning_session_generate_error', error: message }));
    return NextResponse.json({ error: 'Internal server error', requestId }, { status: 500 });
  }
}
