-- ============================================================
-- FILE: supabase/migrations/20260305_elearning_sessions.sql
-- PURPOSE: E-learning session plans (generated by session builder)
-- Creates table, indexes, updated_at trigger, and RLS policies.
-- ============================================================

-- ── Table ──

CREATE TABLE IF NOT EXISTS elearning_sessions (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id              uuid NOT NULL REFERENCES children(id) ON DELETE CASCADE,

  -- Session plan (JSONB) — the full SessionPlan object
  session_plan          jsonb NOT NULL,
  content_ids_used      jsonb DEFAULT '[]'::jsonb,
  intelligence_context  jsonb,

  -- Lifecycle
  started_at            timestamptz,
  completed_at          timestamptz,
  segments_completed    integer NOT NULL DEFAULT 0,
  total_segments        integer NOT NULL,

  -- Generation metadata
  intelligence_generated boolean NOT NULL DEFAULT false,
  estimated_minutes      integer,

  -- Timestamps
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

-- ── Indexes ──

CREATE INDEX idx_elearning_sessions_child_created
  ON elearning_sessions (child_id, created_at DESC);

CREATE INDEX idx_elearning_sessions_active
  ON elearning_sessions (child_id)
  WHERE completed_at IS NULL;

-- ── updated_at trigger ──

CREATE OR REPLACE FUNCTION update_elearning_sessions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_elearning_sessions_updated_at
  BEFORE UPDATE ON elearning_sessions
  FOR EACH ROW
  EXECUTE FUNCTION update_elearning_sessions_updated_at();

-- ── RLS ──

ALTER TABLE elearning_sessions ENABLE ROW LEVEL SECURITY;

-- Parents can read their own children's sessions
CREATE POLICY "Parents can view own children sessions"
  ON elearning_sessions FOR SELECT
  USING (
    child_id IN (
      SELECT id FROM children
      WHERE parent_id = auth.uid()
    )
  );

-- Service role (API routes) can do everything
CREATE POLICY "Service role full access"
  ON elearning_sessions FOR ALL
  USING (auth.role() = 'service_role');
